; Default config for i3bar-workspace-icons

[options]
; General Options

; How many spaces to add between icons. Not all icons can easily fit into one
; character width, so this controls the amount of spaces to separate them.
spacing = 1
; How many icons to show at most per workspace.
max_icons = 4

[override_windows]
; Specify which window classes are allowed to have their icons overridden.
;
; Any window class that matches one of these will have its icon overridden if
; the program detects an override pattern.
;
; Programs with modifiable window titles (like terminal emulators) can have
; their titles modified by other programs. These other programs deserve their
; own icon separate from the "host" program.
alacritty = true
gnome-terminal = true
konsole = true
kitty = true
st = true
foot = true
termite = true
terminator = true
xterm = true
urxvt = true

[override_patterns]
; Specify what patterns in a window title correspond to which window class.
;
; The pattern is currently a simple string match. If a window with an
; overrideable icon (see above) matches a value in this section, the icon will be
; overridden with the icon associated with that window class.
;
; In this case, this config file lets all terminal emulators running Vim or
; Neovim show up as "Vim" and "Neovim" icons.
htop = htop
lvim = Lvim
neovim = Nvim
vim = VIM

[unmatched]
; Specify what to do with unmatched windows
;
; If a window doesn't have a corresponding window class, there is an option to
; display a "default window" icon instead of just nothing.

; Whether to show windows with no corresponding icon in a workspace
show = false
; Default icon for unmatched windows
default = 

[remaining]
; Specify what to do when there are more windows than the max_icons value

; Whether to show how the remaining number of windows in a workspace
show = true

; Icons for 1-9+ additional windows: nf-md-numeric_*_box_multiple
1 = 󰼏
2 = 󰼐
3 = 󰼑
4 = 󰼒
5 = 󰼓
6 = 󰼔
7 = 󰼕
8 = 󰼖
9+ = 󰼘

;; Alternative icons: nf-md-numeric_*_box_multiple_outline
; 1 = 󰎥
; 2 = 󰎨
; 3 = 󰎫
; 4 = 󰎲
; 5 = 󰎯
; 6 = 󰎴
; 7 = 󰎷
; 8 = 󰎺
; 9+ = 󰏀

[window_classes]
; Mapping from (lower-case) window classes to icons. This is by no means an
; exhaustive list, and may be a bit opinionated. I usually strive for what Nerd
; Font symbol most closely resembles the application's icon if there isn't a
; preexisting match.
;
; These don't have to be Nerd Font icons; Any UTF-8 character is allowed.

0ad = ⊕
alacarte = 󰤀
alacritty = 
android-studio = 󰀴
android-studio-beta = 󰀴
android-studio-canary = 󰀴
androidstudio-preview = 󰀴
anki = 󰩳
antigravity = 󰱐
apple-music = 
ardour = 󰔶
arduino = 
arianna = 󰂺
ark = 󰗄
atril = 
audacious = ⓐ
audacity = 
balena-etcher-electron = 󰆧
baobab = 
bitwarden = 
bleachbit = 󰃢
blender = 
bottles = 󰡔
boxy-svg = 󰜡
brave-browser = 🦁
brave-desktop = 🦁
calibre = 󱉟
calibre-ebook-edit = 󱚌
calibre-viewer = 󰺄
chromium = 
chromium-browser = 
clion = 
cmake = 
cmake-gui = 
cmakesetup = 
cmakesetup32 = 
code = 󰨞
datagrip = 
dataspell = 
discord = 
discover = 
dolphin = 󱢴
drawio = 
dropbox = 
drracket = 󰘧
eclipse = 
emacs = 
epiphany = 󰖟
evince = 
filelight = 
firefox = 
firefox-esr = 
foot = 
freecad = 
freecad-daily = 
geogebra = 󱥸
ghostwriter = 󰊠
gimp = 
gitg = 
gitkraken = 
gnome-aisleriot = 󱢡
gnome-character-map = 
gnome-emacs = 
gnome-power-statistics = 
gnome-screenruler = 
gnome-software = 
gnome-terminal = 
godot = 
goland = 
google-chrome = 
google-earth = 󰊷
google-earth-pro = 󰊷
googlechrome = 
googleearth = 󰊷
gparted = 󰋊
grandorgue = 󰙽
gsmartcontrol = 󰋊
gufw = 󰞀
gvim = 
gwenview = 󰈈
helix = 
htop = 
inkscape = 
intellij = 
itch = 
joplin = 󰬑
joplin-desktop = 󰬑
julia = 
juliabackend = 
kcalc = 
kde-connect = 
kdenlive = 
kicad = 
kitty = 
knights = 
kodi = 󰌔
kolourpaint = 
konsole = 
krita = 
kruler = 
ksudoku = 󰋁
lazpaint = 
libre-menu-editor = 󰤀
libreoffice = 
libreoffice-base = 
libreoffice-calc = 
libreoffice-draw = 
libreoffice-impress = 
libreoffice-math = 
libreoffice-writer = 
librewolf = 🐺
liferea = 
logisim = 󰣥
logisimevolution = 󰣥
lutris = 
lvim = 
maple = 󰲓
matlab = 
matlab-desktop = 
matlab_icon = 
microsoft-edge = 
minecraft = 󰍳
mpv = 
mupdf = 
musescore = 󰰢
neovide = 
neovim = 
nvim-gtk = 
nvim-qt = 
obsidian = 🪨
okular = 
openscad = 
openshot = 󰇧
openshot-qt = 󰇧
opentoonz = 
opera = 
org.gnome.boxes = 
org.gnome.dejadup = 󱉼
org.gnome.evolution = 
org.gnome.nautilus = 󰪶
org.gnome.web = 󰖟
palapeli = 󰐱
pamac = 
pamac-manager = 
pamac-updater = 
pavucontrol = 
phpstorm = 
pidgin = 
pinta = 
podman = 
postman = 
prismlauncher = 󰆧
prusa-slicer = 
prusa-slicer-gcodeviewer = 
prusaslicer = 
prusaslicer-gcodeviewer = 
pycharm = 
qutebrowser = 󰖟
retroarch = 󰯉
rider = 
rpi-imager = 
rstudio = 
rubymine = 
scribus = 󰴒
scribus-ng = 󰴒
scribus-trunk = 󰴒
setzer = 󱗆
slack = 
spectacle = 󰹑
steam = 
sublime = 
sublime-merge = 
sublime-text = 
sublimetext = 
synaptic = 󰏓
teams-for-linux = 󰊻
texmaker = 
texstudio = 
thunderbird = 
thunderbird-esr = 
timeshift = 𝕿
tor = 
tor-browser = 
torbrowser = 
unciv = 󰛡
ungoogled-chromium = 
unityeditor = 
unityhub = 
vim = 
visual-studio-code = 󰨞
vlc = 󰕼
vscode = 󰨞
vscodium = 
webstorm = 
wezterm = 󰬞
whatsapp = 
whatsapp-business = 
whatsapp-desktop = 
whatsapp-for-linux = 
whatsapp-nativefier = 
whatsdesk = 
wine = 󰡶
wireshark = 󱙳
yandex = 
zed = 󰰶
zoom = 󰰷
zotero = 󰬡
