"""Build the `README.md` file for this program."""

from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from i3bar_workspace_icons import parser

TEMPLATES_DIR = Path("doc/templates")
README_MD_JINJA = "readme.md.jinja"
README_MD = Path("README.md")
AUTOGENERATED_WARNING = (
    "<!-- This file is auto-generated. Don't edit it manually; instead, edit `%s`. -->"
    % (TEMPLATES_DIR / README_MD_JINJA)
)


env = Environment(loader=FileSystemLoader("doc/templates"))


def build_readme() -> None:
    """Build the `README.md` file for this program."""
    help_output = parser.format_help()
    template = env.get_template(README_MD_JINJA)
    README_MD.write_text(
        template.render(
            autogenerated_warning=AUTOGENERATED_WARNING, help_output=help_output
        ),
    )


if __name__ == "__main__":
    build_readme()
