"""Build the `README.md` file for this program."""

from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from i3bar_workspace_icons import parser

AUTOGENERATED_WARNING = (
    """<!-- This file is auto-generated by the `scripts/build_readme.py` script. -->"""
)


def build_readme() -> None:
    """Build the `README.md` file for this program."""
    env = Environment(loader=FileSystemLoader("doc/templates"))
    help_output = parser.format_help()

    template = env.get_template("README.md.jinja")
    readme_path = Path("README.md")
    readme_path.write_text(
        template.render(
            autogenerated_warning=AUTOGENERATED_WARNING, help_output=help_output
        ),
    )


if __name__ == "__main__":
    build_readme()
