# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main", "release/*"]
  pull_request:
    branches: ["main", "release/*"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --group dev --editable .
      - name: Lint with Ruff
        run: |
          ruff check .
      - name: Type-Check with Pyrefly
        run: |
          pyrefly check
      - name: Test with Pytest
        run: |
          pytest
      - name: Debug & Dry-Run
        run: |
          python3 -m venv .venv --prompt=i3bar-workspace-icons
          source .venv/bin/activate
          pip install --editable .
          i3bar-workspace-icons --debug --dry-run
          i3bar-workspace-icons --debug --dry-run --version
          i3bar-workspace-icons --debug --dry-run --dump-config
          i3bar-workspace-icons --debug --dry-run --configfile ./src/i3bar_workspace_icons/default_config.ini
          pip install .
          i3bar-workspace-icons --debug --dry-run
          i3bar-workspace-icons --debug --dry-run --version
          i3bar-workspace-icons --debug --dry-run --dump-config
          i3bar-workspace-icons --debug --dry-run --configfile ./src/i3bar_workspace_icons/default_config.ini
